# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f6165095ad868c857ae0e6b78e70013"
name = "testshop24"
application_url = "http://localhost:3001"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_product_listings,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "http://localhost:3001/shopify/callback" ]

[pos]
embedded = false
